# Generated by Django 3.2.25 on 2025-01-27 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profile_picture",
            field=models.ImageField(
                default="default.jpg", upload_to="profile_pics/user.username"
            ),
        ),
    ]
