# Generated by Django 5.2.1 on 2025-06-07 20:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0002_alter_profile_profile_picture"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="portfolio",
            name="image",
        ),
        migrations.RemoveField(
            model_name="portfolio",
            name="profile",
        ),
        migrations.RemoveField(
            model_name="portfolio",
            name="project_url",
        ),
        migrations.RemoveField(
            model_name="portfolio",
            name="technologies_used",
        ),
        migrations.AddField(
            model_name="portfolio",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="portfolio",
            name="related_job",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="portfolio",
            name="role",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="portfolio",
            name="skills",
            field=models.CharField(
                default="None",
                help_text="Comma-separated list of skills used in the project",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="portfolio",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="portfolio",
            name="description",
            field=models.TextField(max_length=600),
        ),
        migrations.AlterField(
            model_name="portfolio",
            name="title",
            field=models.CharField(max_length=70),
        ),
        migrations.CreateModel(
            name="PortfolioSample",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("completion_date", models.DateField()),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="portfolio/images/"
                    ),
                ),
                (
                    "video",
                    models.FileField(
                        blank=True, null=True, upload_to="portfolio/videos/"
                    ),
                ),
                (
                    "audio",
                    models.FileField(
                        blank=True, null=True, upload_to="portfolio/audio/"
                    ),
                ),
                (
                    "pdf",
                    models.FileField(
                        blank=True, null=True, upload_to="portfolio/pdfs/"
                    ),
                ),
                ("url", models.URLField(blank=True, null=True)),
                ("text_block", models.TextField(blank=True, null=True)),
                (
                    "portfolio",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="portfolio_samples",
                        to="profiles.portfolio",
                    ),
                ),
            ],
        ),
    ]
