# Generated by Django 5.2.1 on 2025-06-07 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0004_alter_portfolio_created_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="portfoliosample",
            name="completion_date",
        ),
    ]
