# Generated by Django 5.2.1 on 2025-06-08 00:04

import django.db.models.deletion
import profiles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0005_remove_portfoliosample_completion_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="portfolio",
            name="sample",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sample_instance",
                to="profiles.portfoliosample",
            ),
        ),
        migrations.AlterField(
            model_name="portfoliosample",
            name="audio",
            field=models.FileField(
                blank=True, null=True, upload_to=profiles.models.portfolio_file_path
            ),
        ),
        migrations.AlterField(
            model_name="portfoliosample",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to=profiles.models.portfolio_file_path
            ),
        ),
        migrations.AlterField(
            model_name="portfoliosample",
            name="pdf",
            field=models.FileField(
                blank=True, null=True, upload_to=profiles.models.portfolio_file_path
            ),
        ),
        migrations.AlterField(
            model_name="portfoliosample",
            name="portfolio",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="portfolio_samples",
                to="profiles.portfolio",
            ),
        ),
        migrations.AlterField(
            model_name="portfoliosample",
            name="video",
            field=models.FileField(
                blank=True, null=True, upload_to=profiles.models.portfolio_file_path
            ),
        ),
    ]
