# Generated by Django 5.2.1 on 2025-06-08 00:13

import profiles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0006_portfolio_sample_alter_portfoliosample_audio_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="portfoliosample",
            name="image",
        ),
        migrations.AddField(
            model_name="portfolio",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to=profiles.models.portfolio_file_path
            ),
        ),
    ]
