# Generated by Django 5.2.1 on 2025-06-08 10:09

import django.db.models.deletion
import profiles.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0007_remove_portfoliosample_image_portfolio_image"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="IdentityVerification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "id_card",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=profiles.models.identity_verification_file_path,
                    ),
                ),
                ("id_card_verified", models.BooleanField(default=False)),
                ("id_card_verified_at", models.DateTimeField(blank=True, null=True)),
                ("id_card_rejection_reason", models.TextField(blank=True, null=True)),
                (
                    "face_photo",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=profiles.models.identity_verification_file_path,
                    ),
                ),
                ("face_photo_verified", models.BooleanField(default=False)),
                ("face_photo_verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "face_photo_rejection_reason",
                    models.TextField(blank=True, null=True),
                ),
                (
                    "proof_of_residence",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=profiles.models.identity_verification_file_path,
                    ),
                ),
                ("proof_of_residence_verified", models.BooleanField(default=False)),
                (
                    "proof_of_residence_verified_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "proof_of_residence_rejection_reason",
                    models.TextField(blank=True, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VehicleDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "drivers_license",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=profiles.models.vehicle_file_path,
                    ),
                ),
                ("drivers_license_verified", models.BooleanField(default=False)),
                (
                    "drivers_license_verified_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "drivers_license_rejection_reason",
                    models.TextField(blank=True, null=True),
                ),
                (
                    "blue_book",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=profiles.models.vehicle_file_path,
                    ),
                ),
                ("blue_book_verified", models.BooleanField(default=False)),
                ("blue_book_verified_at", models.DateTimeField(blank=True, null=True)),
                ("blue_book_rejection_reason", models.TextField(blank=True, null=True)),
                (
                    "inspection_certificate",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=profiles.models.vehicle_file_path,
                    ),
                ),
                ("inspection_certificate_verified", models.BooleanField(default=False)),
                (
                    "inspection_certificate_verified_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "inspection_certificate_rejection_reason",
                    models.TextField(blank=True, null=True),
                ),
                (
                    "insurance",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=profiles.models.vehicle_file_path,
                    ),
                ),
                ("insurance_verified", models.BooleanField(default=False)),
                ("insurance_verified_at", models.DateTimeField(blank=True, null=True)),
                ("insurance_rejection_reason", models.TextField(blank=True, null=True)),
                (
                    "tax_document",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=profiles.models.vehicle_file_path,
                    ),
                ),
                ("tax_document_verified", models.BooleanField(default=False)),
                (
                    "tax_document_verified_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "tax_document_rejection_reason",
                    models.TextField(blank=True, null=True),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="taxiverificationdocument",
            name="profile",
        ),
        migrations.RemoveField(
            model_name="taxiverificationdocument",
            name="verified_by",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="background_check_date",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="background_check_status",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="business_license",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="id_document",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="insurance_document",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="is_verified",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="verification_status",
        ),
        migrations.RemoveField(
            model_name="vehicle",
            name="inspection_certificate",
        ),
        migrations.RemoveField(
            model_name="vehicle",
            name="insurance",
        ),
        migrations.RemoveField(
            model_name="vehicle",
            name="registration",
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="license_plate",
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AddIndex(
            model_name="vehicle",
            index=models.Index(
                fields=["license_plate"], name="profiles_ve_license_5f384f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vehicle",
            index=models.Index(
                fields=["is_active", "is_verified"],
                name="profiles_ve_is_acti_c4f11f_idx",
            ),
        ),
        migrations.AddField(
            model_name="identityverification",
            name="face_photo_verified_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="verified_face_photos",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="identityverification",
            name="id_card_verified_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="verified_id_cards",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="identityverification",
            name="profile",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="identity_verification",
                to="profiles.profile",
            ),
        ),
        migrations.AddField(
            model_name="identityverification",
            name="proof_of_residence_verified_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="verified_proofs_of_residence",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="vehicledocument",
            name="blue_book_verified_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="verified_blue_books",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="vehicledocument",
            name="drivers_license_verified_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="verified_drivers_licenses",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="vehicledocument",
            name="inspection_certificate_verified_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="verified_inspection_certificates",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="vehicledocument",
            name="insurance_verified_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="verified_insurances",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="vehicledocument",
            name="tax_document_verified_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="verified_tax_documents",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="vehicledocument",
            name="vehicle",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="profiles.vehicle",
            ),
        ),
        migrations.DeleteModel(
            name="TaxiVerificationDocument",
        ),
        migrations.AddIndex(
            model_name="identityverification",
            index=models.Index(
                fields=[
                    "id_card_verified",
                    "face_photo_verified",
                    "proof_of_residence_verified",
                ],
                name="profiles_id_id_card_f90dc2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="vehicledocument",
            index=models.Index(
                fields=[
                    "drivers_license_verified",
                    "blue_book_verified",
                    "inspection_certificate_verified",
                    "insurance_verified",
                    "tax_document_verified",
                ],
                name="profiles_ve_drivers_77dbaa_idx",
            ),
        ),
    ]
