# Generated by Django 5.2.1 on 2025-06-18 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0009_identityverification_vehicledocument_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="account_type",
            field=models.CharField(
                choices=[
                    ("REGULAR", "Regular User"),
                    ("TAXI", "Taxi Service Provider"),
                    ("DELIVERY", "Delivery Service Provider"),
                ],
                default="REGULAR",
                max_length=10,
            ),
        ),
    ]
