# Generated by Django 5.2.1 on 2025-06-27 12:06

import django.core.validators
import profiles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0010_alter_profile_account_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="identityverification",
            name="face_photo",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=profiles.models.identity_verification_file_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="identityverification",
            name="id_card",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=profiles.models.identity_verification_file_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png", "pdf"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="identityverification",
            name="proof_of_residence",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=profiles.models.identity_verification_file_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png", "pdf"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="vehicledocument",
            name="blue_book",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=profiles.models.vehicle_file_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png", "pdf"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="vehicledocument",
            name="drivers_license",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=profiles.models.vehicle_file_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png", "pdf"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="vehicledocument",
            name="inspection_certificate",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=profiles.models.vehicle_file_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png", "pdf"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="vehicledocument",
            name="insurance",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=profiles.models.vehicle_file_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png", "pdf"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="vehicledocument",
            name="tax_document",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=profiles.models.vehicle_file_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png", "pdf"]
                    )
                ],
            ),
        ),
    ]
