# Generated by Django 5.2.1 on 2025-06-28 16:46

import django.core.validators
import django.db.models.deletion
import profiles.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0011_alter_identityverification_face_photo_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GovernmentPermit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "permit_type",
                    models.CharField(
                        choices=[
                            ("TAXI", "Taxi PSV Permit"),
                            ("DELIVERY", "Delivery PSV Permit"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "permit_document",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=profiles.models.permit_file_path,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["jpg", "jpeg", "png", "pdf"]
                            )
                        ],
                    ),
                ),
                ("permit_number", models.CharField(max_length=50, unique=True)),
                ("issue_date", models.DateField()),
                ("expiry_date", models.DateField()),
                ("is_verified", models.BooleanField(default=False)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveIndex(
            model_name="vehicledocument",
            name="profiles_ve_drivers_77dbaa_idx",
        ),
        migrations.RemoveField(
            model_name="vehicledocument",
            name="tax_document",
        ),
        migrations.RemoveField(
            model_name="vehicledocument",
            name="tax_document_rejection_reason",
        ),
        migrations.RemoveField(
            model_name="vehicledocument",
            name="tax_document_verified",
        ),
        migrations.RemoveField(
            model_name="vehicledocument",
            name="tax_document_verified_at",
        ),
        migrations.RemoveField(
            model_name="vehicledocument",
            name="tax_document_verified_by",
        ),
        migrations.AlterField(
            model_name="profile",
            name="phone_number",
            field=models.CharField(
                blank=True,
                max_length=17,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be in Eswatini format: '+268 7XXX XXXX' or '+268 2XXX XXXX'.",
                        regex="^\\+268\\d{7,8}$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="title",
            field=models.CharField(
                blank=True,
                help_text="Professional title, e.g. 'Taxi Driver'",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="last_inspection_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="license_plate",
            field=models.CharField(
                max_length=10,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="License plate must follow Eswatini format (e.g., JSD 123 AM)",
                        regex="^[A-Z]SD\\s\\d{3}\\s[A-Z][A-Z]$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="next_inspection_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="vehicle_type",
            field=models.CharField(
                choices=[
                    ("CAR", "Car"),
                    ("VAN", "Van"),
                    ("TRUCK", "Truck"),
                    ("MOTORCYCLE", "Motorcycle"),
                    ("TAXI", "Taxi"),
                    ("DELIVERY", "Delivery Vehicle"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="vehicledocument",
            index=models.Index(
                fields=[
                    "drivers_license_verified",
                    "blue_book_verified",
                    "inspection_certificate_verified",
                    "insurance_verified",
                ],
                name="profiles_ve_drivers_03dc1e_idx",
            ),
        ),
        migrations.AddField(
            model_name="governmentpermit",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="government_permits",
                to="profiles.profile",
            ),
        ),
        migrations.AddField(
            model_name="governmentpermit",
            name="verified_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="verified_permits",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="governmentpermit",
            index=models.Index(
                fields=["permit_type", "is_verified"],
                name="profiles_go_permit__aa32b1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="governmentpermit",
            index=models.Index(
                fields=["permit_number"], name="profiles_go_permit__9f6cac_idx"
            ),
        ),
    ]
