# Generated by Django 5.2.1 on 2025-06-29 07:19

import django.core.validators
import django.db.models.deletion
import profiles.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0012_governmentpermit_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicle",
            name="operators",
            field=models.ManyToManyField(
                blank=True,
                related_name="operated_vehicles",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="account_type",
            field=models.CharField(
                choices=[
                    ("REGULAR", "Regular User"),
                    ("TRANSPORT", "Transport Service Provider"),
                ],
                default="REGULAR",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="title",
            field=models.CharField(
                blank=True,
                help_text="Professional title, e.g. 'Transport Service Provider'",
                max_length=200,
            ),
        ),
        migrations.CreateModel(
            name="OperatorDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "drivers_license",
                    models.FileField(
                        upload_to=profiles.models.operator_document_file_path,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["jpg", "jpeg", "png", "pdf"]
                            )
                        ],
                    ),
                ),
                ("drivers_license_verified", models.BooleanField(default=False)),
                (
                    "drivers_license_verified_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "drivers_license_rejection_reason",
                    models.TextField(blank=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "drivers_license_verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="operator_license_verified",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="operator_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="operator_documents",
                        to="profiles.vehicle",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["drivers_license_verified"],
                        name="profiles_op_drivers_0dff70_idx",
                    ),
                    models.Index(
                        fields=["user", "vehicle"],
                        name="profiles_op_user_id_b9106e_idx",
                    ),
                ],
                "unique_together": {("user", "vehicle")},
            },
        ),
    ]
