# Generated by Django 5.2.1 on 2025-06-30 19:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0013_vehicle_operators_alter_profile_account_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehicle",
            name="license_plate",
            field=models.CharField(
                max_length=10,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="License plate must follow Eswatini format (e.g., JSD 123 AM)",
                        regex="^[A-Z]SD\\s\\d{3}\\s[A-Z]{2}$",
                    )
                ],
            ),
        ),
    ]
