# Generated by Django 4.2.11 on 2025-08-17 19:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("profiles", "0017_vehicle_document_workflow"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="transport_owner_tag",
            field=models.BooleanField(
                default=False,
                help_text="True if user qualifies as a Transport Owner based on document approvals",
            ),
        ),
        migrations.CreateModel(
            name="OperatorAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                (
                    "active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this assignment is currently active",
                    ),
                ),
                ("deactivated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "assigned_by",
                    models.ForeignKey(
                        help_text="Vehicle owner who made the assignment",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assigned_operators",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "operator",
                    models.ForeignKey(
                        help_text="User assigned as operator for this vehicle",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assigned_vehicles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vehicle",
                    models.OneToOneField(
                        help_text="Vehicle being assigned to an operator",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="operator_assignment",
                        to="profiles.vehicleownership",
                    ),
                ),
            ],
            options={
                "ordering": ["-assigned_at"],
                "indexes": [
                    models.Index(
                        fields=["vehicle", "active"],
                        name="profiles_op_vehicle_ed2b97_idx",
                    ),
                    models.Index(
                        fields=["operator", "active"],
                        name="profiles_op_operato_1849f9_idx",
                    ),
                    models.Index(
                        fields=["assigned_at"], name="profiles_op_assigne_5f1b12_idx"
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="operatorassignment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("active", True)),
                fields=("vehicle",),
                name="one_active_operator_per_vehicle",
            ),
        ),
    ]
