# Generated by Django 4.2.11 on 2025-08-19 01:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("profiles", "0018_operator_assignment_system"),
    ]

    operations = [
        migrations.CreateModel(
            name="TransportOwnerBadge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "authorized",
                    models.BooleanField(
                        default=False,
                        help_text="Whether user is authorized as a transport provider",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transport_badge",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["authorized"], name="profiles_tr_authori_3ad29b_idx"
                    ),
                    models.Index(
                        fields=["updated_at"], name="profiles_tr_updated_a11cae_idx"
                    ),
                ],
            },
        ),
    ]
