# Generated by Django 4.2.11 on 2025-08-20 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0019_transportownerbadge"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="doc_type",
            field=models.CharField(
                choices=[
                    ("ROADWORTHY", "Roadworthiness Certificate"),
                    ("BLUEBOOK", "Registration Certificate (Blue Book)"),
                    ("DRIVER_LICENSE", "Driver's License"),
                    ("PERMIT", "PSV Permit"),
                    ("ID_CARD", "Government ID Card"),
                    ("FACE_PHOTO", "Face Photo"),
                    ("PROOF_OF_RESIDENCE", "Proof of Residence"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="vehicle",
            field=models.ForeignKey(
                blank=True,
                help_text="Leave blank for user-only documents like driver's license",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="generic_documents",
                to="profiles.vehicleownership",
            ),
        ),
    ]
