# Generated by Django 5.2.1 on 2025-06-11 19:18

import chat.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="messageattachment",
            name="file",
            field=models.FileField(upload_to=chat.models.message_attachment_path),
        ),
        migrations.DeleteModel(
            name="ProjectChatNotification",
        ),
    ]
