# Generated by Django 3.2.25 on 2025-02-08 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallets", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="payment_method",
            field=models.CharField(
                choices=[("MOMO", "MTN Mobile Money"), ("eMALI", "e-Mali")],
                default="MOMO",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("DEPOSIT", "Deposit"),
                    ("WITHDRAWAL", "Withdrawal"),
                    ("PAYMENT", "Project Payment"),
                    ("REFUND", "Project Refund"),
                ],
                max_length=20,
            ),
        ),
    ]
