# Generated by Django 5.2.1 on 2025-06-21 11:40

import django.db.models.deletion
import wallets.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallets", "0002_auto_20250208_1138"),
    ]

    operations = [
        migrations.AlterField(
            model_name="momopayment",
            name="phone_number",
            field=models.CharField(
                max_length=12,
                validators=[wallets.models.validate_swaziland_phone_number],
            ),
        ),
        migrations.AlterField(
            model_name="momopayment",
            name="transaction",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="momopayment",
                to="wallets.transaction",
            ),
        ),
    ]
