# Generated by Django 5.2.1 on 2025-06-18 19:23

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransportContractTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('TAXI', 'Taxi'), ('DELIVERY', 'Delivery'), ('DEFAULT', 'Default')], default='DEFAULT', max_length=20, unique=True)),
                ('terms', models.TextField(help_text='Use placeholders: {service_type}, {agreed_amount}, {pickup_location}, {dropoff_location}, {client_name}, {provider_name}, {job_id}')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Transport Contract Template',
                'verbose_name_plural': 'Transport Contract Templates',
            },
        ),
        migrations.CreateModel(
            name='TransportRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('TAXI', 'Taxi'), ('DELIVERY', 'Delivery')], default='TAXI', max_length=20)),
                ('pickup_location', models.CharField(max_length=255)),
                ('pickup_latitude', models.FloatField()),
                ('pickup_longitude', models.FloatField()),
                ('dropoff_location', models.CharField(max_length=255)),
                ('dropoff_latitude', models.FloatField()),
                ('dropoff_longitude', models.FloatField()),
                ('pickup_time', models.DateTimeField()),
                ('budget', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('estimated_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('distance_km', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('route_polyline', models.TextField(blank=True, help_text='Encoded polyline for the route', null=True)),
                ('estimated_time', models.IntegerField(blank=True, help_text='Estimated travel time in minutes', null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('ACCEPTED', 'Accepted'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='OPEN', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('rating', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('review', models.TextField(blank=True, null=True)),
                ('load_image', models.ImageField(blank=True, null=True, upload_to='job_loads/%Y/%m/%d/')),
                ('is_urgent', models.BooleanField(default=False)),
                ('vehicle_type_required', models.CharField(choices=[('CAR', 'Car'), ('VAN', 'Van'), ('TRUCK', 'Truck'), ('MOTORCYCLE', 'Motorcycle'), ('ANY', 'Any Vehicle')], default='ANY', max_length=20)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_requests', to=settings.AUTH_USER_MODEL)),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='provided_jobs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TransportContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agreed_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('terms', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('confirmed_by_provider', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_contracts', to=settings.AUTH_USER_MODEL)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to=settings.AUTH_USER_MODEL)),
                ('transport_job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contract', to='transport.transportrequest')),
            ],
        ),
        migrations.CreateModel(
            name='TransportBid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('proposal', models.TextField(blank=True, null=True)),
                ('estimated_completion_time', models.IntegerField(blank=True, help_text='Estimated time in minutes', null=True)),
                ('vehicle_type', models.CharField(choices=[('CAR', 'Car'), ('VAN', 'Van'), ('TRUCK', 'Truck'), ('MOTORCYCLE', 'Motorcycle'), ('ANY', 'Any Vehicle')], default='ANY', max_length=20)),
                ('job_sample', models.FileField(blank=True, null=True, upload_to='bid_samples/%Y/%m/%d/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to=settings.AUTH_USER_MODEL)),
                ('transport_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='transport.transportrequest')),
            ],
        ),
        migrations.AddIndex(
            model_name='transportrequest',
            index=models.Index(fields=['client', 'status'], name='transport_t_client__4dc5a0_idx'),
        ),
        migrations.AddIndex(
            model_name='transportrequest',
            index=models.Index(fields=['provider', 'status'], name='transport_t_provide_b8d746_idx'),
        ),
    ]
