# Generated by Django 5.2.1 on 2025-06-28 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportbid',
            name='vehicle_type',
            field=models.CharField(choices=[('CAR', 'Car'), ('VAN', 'Van'), ('TRUCK', 'Truck'), ('MOTORCYCLE', 'Motorcycle'), ('TAXI', 'Taxi'), ('DELIVERY', 'Delivery Vehicle'), ('ANY', 'Any Vehicle')], default='ANY', max_length=20),
        ),
        migrations.AlterField(
            model_name='transportrequest',
            name='vehicle_type_required',
            field=models.CharField(choices=[('CAR', 'Car'), ('VAN', 'Van'), ('TRUCK', 'Truck'), ('MOTORCYCLE', 'Motorcycle'), ('TAXI', 'Taxi'), ('DELIVERY', 'Delivery Vehicle'), ('ANY', 'Any Vehicle')], default='ANY', max_length=20),
        ),
    ]
