# Generated by Django 5.2.1 on 2025-06-18 21:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("chat", "0002_alter_messageattachment_file_and_more"),
        ("projects", "0001_initial"),
        ("transport", "0001_initial"),
        ("wallets", "0002_auto_20250208_1138"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminReminder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("send_to_all", models.BooleanField(default=False)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sent_reminders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "recipients",
                    models.ManyToManyField(
                        blank=True,
                        related_name="received_reminders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_read", models.BooleanField(default=False)),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("profile_completion", "Profile Completion"),
                            ("admin_reminder", "Admin Reminder"),
                            ("chat_message", "Chat Message"),
                            ("milestone_due", "Milestone Due Soon"),
                            ("file_uploaded", "File Uploaded"),
                            ("proposal_update", "Proposal Updated"),
                            ("status_change", "Project Status Changed"),
                            ("review_requested", "Review Requested"),
                            ("project_update", "Project Update"),
                            ("wallet_transaction", "Wallet Transaction"),
                            ("project_fund", "Project Fund Update"),
                            ("transport_bid_submitted", "Bid Submitted"),
                            ("transport_bid_accepted", "Bid Accepted"),
                            ("transport_contract_confirmed", "Contract Confirmed"),
                            ("transport_job_status_updated", "Job Status Updated"),
                            ("transport_job_deleted", "Job Deleted"),
                            ("project_created", "Project Created"),
                            ("project_proposal", "Project Proposal"),
                            ("project_proposal_accepted", "Proposal Accepted"),
                            ("project_status_update", "Project Status Update"),
                            ("project_review", "Project Review"),
                            ("project_rating", "Project Rating"),
                        ],
                        max_length=50,
                    ),
                ),
                ("link", models.URLField(blank=True, null=True)),
                (
                    "chat_message",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notifications",
                        to="chat.message",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notifications",
                        to="projects.project",
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notifications",
                        to="wallets.transaction",
                    ),
                ),
                (
                    "transport_request",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notifications",
                        to="transport.transportrequest",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
