# Generated by Django 4.2.11 on 2025-08-24 16:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("notifications", "0004_remove_taxi_delivery_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("profile_completion", "Profile Completion"),
                    ("admin_reminder", "Admin Reminder"),
                    ("chat_message", "Chat Message"),
                    ("milestone_due", "Milestone Due Soon"),
                    ("file_uploaded", "File Uploaded"),
                    ("proposal_update", "Proposal Updated"),
                    ("status_change", "Project Status Changed"),
                    ("review_requested", "Review Requested"),
                    ("project_update", "Project Update"),
                    ("wallet_transaction", "Wallet Transaction"),
                    ("project_fund", "Project Fund Update"),
                    ("transport_bid_submitted", "Bid Submitted"),
                    ("transport_bid_accepted", "Bid Accepted"),
                    ("transport_contract_confirmed", "Contract Confirmed"),
                    ("transport_job_status_updated", "Job Status Updated"),
                    ("transport_job_deleted", "Job Deleted"),
                    ("project_created", "Project Created"),
                    ("project_proposal", "Project Proposal"),
                    ("project_proposal_accepted", "Proposal Accepted"),
                    ("project_status_update", "Project Status Update"),
                    ("project_review", "Project Review"),
                    ("project_rating", "Project Rating"),
                    ("document_approved", "Document Approved"),
                    ("document_rejected", "Document Rejected"),
                    ("general", "General Notification"),
                ],
                default="general",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="title",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="notification",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_notifications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["user", "is_read"], name="notificatio_user_id_427e4b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["created_at"], name="notificatio_created_46ad24_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["notification_type"], name="notificatio_notific_f2898f_idx"
            ),
        ),
    ]
