name: CI

on:
  pull_request:
  push:
    branches: ["profiles-overhaul", "feat/**"]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          
      - name: Install dependencies
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt || true
          pip install django pytest pytest-django black ruff django-environ
          
      - name: Lint with ruff
        run: |
          ruff check .
          
      - name: Format check with black
        run: |
          black --check .
          
      - name: Run tests
        env:
          SECRET_KEY: test-secret-key-for-ci
          DEBUG: "True"
        run: |
          pytest -q
